apiVersion: v1
kind: Service
metadata:
  name: dental-backend-service
spec:
  type: LoadBalancer
  selector:
    app: dental-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
